---
title: "DGS_S1_analyses"
author: "Qilin Zhang"
date: "2023-02-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###load packages

```{r pac, message = FALSE, include=FALSE}
library(summarytools)
library(tidyverse) #data wrangling
library(codebook) #codebook generation
library(future) #reliability
library(ufs) #reliability
library(GGally) #reliability
library(GPArotation) #reliability
library(rio) #reading in different file types
library(labelled) #labeling data
library(psych)
library(corrplot) 
library("psych")
library(mirt)
library(eRm)
library(mice)
library(lavaan)
library(semPlot)
library(parameters)
library(broom)
library(likert)

#if need to download the epmr package
#if (!require("devtools")) install.packages("devtools")   
#devtools::install_github("talbano/epmr")
```

### cleaning


```{r cleaning code, include = FALSE}

## use other read functions as appropriate for file type

dict <- rio::import(file = "data/DGS_S1_dictionary.xlsx") #dictionary

data <- read.csv(file = 'data/DGS_S1_Deidentified For Analyses.csv', sep = ",") #data

data <- data[-c(1:2),-c(1:7)]

## Variable types 
names <- dict %>% 
  filter(type == "character") %>% 
  pull(variable)
data[,names] <- 
  lapply(data[,names], as.character)

names <- dict %>% 
  filter(type == "factor") %>% 
  pull(variable)
data[,names] <- 
  lapply(data[,names], as.numeric) #factor variables are coded as numeric for codebook purposes

names <- dict %>% 
  filter(type == "numeric") %>% 
  pull(variable)
data[,names] <- 
  lapply(data[,names], as.numeric)

rm(names)

##data completion check and imputation

#remove failed attention check -55 participants from this process
data <- data %>%
  filter(DGS_31 == 4) %>%
  filter((DGS_53 == 2))


#function for checking percentage of missing data (unit=%)
percent_missing <- function(x){
  sum(is.na((x))/length(x)*100)
}
missing_R <- apply(data,1,percent_missing)
table(missing_R)

#use if don't want imputation(turn off if I need imputation)
replace_rows <- subset(data, missing_R<=0)
data <- replace_rows
```

```{r imputation, include= FALSE}
if(FALSE){
#subset based on filtering criteria
replace_rows <- subset(data, missing_R<=10)
no_rows <- subset(data, missing_R>10)

missing_C <- apply(replace_rows,2,percent_missing)
table(missing_C) #no concern here

replace_data <- replace_rows[,1:85]
leftout <- replace_rows[,86:91]

#check where the NAs are if needed
rindex <- rep(FALSE, nrow(replace_data))
for (i in 1:nrow(replace_data)){
  for (j in 1:grep("DGS_75",colnames(replace_data))){
    if( is.na(replace_data[i,j])){
      rindex[i] = TRUE
      j = ncol(replace_data)+1
    }
  }
}
data_error <- replace_data[rindex,]

rm(data_error)
#imputation
temp <- mice(replace_data)
fixed_data <- complete(temp)  #imputation using mice package
data <- cbind(fixed_data,leftout) #no additional participants were removed

rm(fixed_data,leftout,no_rows,replace_data,replace_rows)
}
```

```{r recode, include=FALSE}
##recode

#DGS recode
likert <- dict %>% 
  filter (value_label == "1 = Strongly disagree, 2 = Disagree, 3 = Somewhat disagree, 4 = Neither agree nor disagree, 5 = Somewhat agree, 6 = Agree, 7 = Strongly agree") %>%
  pull(variable)
add_likert <- function(x) {
  val_labels(x) <- c("Strongly disagree"= 1, "Disagree" = 2, "Somewhat disagree" = 3, "Neither agree nor disagree" = 4, "Somewhat agree" = 5, "Agree" = 6, "Strongly agree" = 7) 
  x
}
data <- data %>%
  mutate_at(likert, 
            add_likert)  

rm(likert, add_likert)

#HEXACO_C

likert <- dict %>% 
  filter (value_label == "1 = Strongly disagree, 2 = Somewhat disagree, 3 = Neither agree nor disagree, 4 = Somewhat agree, 5 = Strongly agree") %>%
  pull(variable)
add_likert <- function(x) {
  val_labels(x) <- c("Strongly disagree"= 1, "Somewhat disagree" = 2, "Neither agree nor disagree" = 3, "Somewhat agree" = 4, "Strongly agree" = 5) 
  x
}
data <- data %>%
  mutate_at(likert, 
            add_likert)  

rm(likert, add_likert)

## Reverse-scoring 
reversed_items <- dict %>%  #make a list of reversed items
 filter (keying == -1) %>% 
 pull(variable)

data <- data %>%  #reverse values in data
  mutate_at(reversed_items,
          reverse_labelled_values)

rm(reversed_items)

##scale construction

## Variable labels
var_label(data) <- dict %>% 
  select(variable, label) %>% 
  dict_to_list()

rm(extra)

##DGS
DGS <- dict %>% 
  filter (scale == "DGS") %>% 
  pull(variable)

data$DGS <- data %>% 
  select(all_of(DGS)) %>% 
  aggregate_and_document_scale()

##HEXACO_C

HEXACO_C <- dict %>% 
  filter (scale == "HEXACO_C") %>% 
  pull(variable)

data$HEXACO_C <- data %>% 
  select(all_of(HEXACO_C)) %>% 
  aggregate_and_document_scale()

###7 factors model
M7_1 <- dict %>% 
  filter (M7_concise == 1) %>% 
  pull(variable)
M7_2 <- dict %>% 
  filter (M7_concise == 2) %>% 
  pull(variable)
M7_3 <- dict %>% 
  filter (M7_concise == 3) %>% 
  pull(variable)
M7_4 <- dict %>% 
  filter (M7_concise == 4) %>% 
  pull(variable)
M7_5 <- dict %>% 
  filter (M7_concise == 5) %>% 
  pull(variable)
M7_6 <- dict %>% 
  filter (M7_concise == 6) %>% 
  pull(variable)
M7_7 <- dict %>% 
  filter (M7_concise == 7) %>% 
  pull(variable)

###7 factors model

data$M7_1 <- data %>% 
  select(all_of(M7_1)) %>% 
  aggregate_and_document_scale()

data$M7_2 <- data %>% 
  select(all_of(M7_2)) %>% 
  aggregate_and_document_scale()

data$M7_3 <- data %>% 
  select(all_of(M7_3)) %>% 
  aggregate_and_document_scale()

data$M7_4 <- data %>% 
  select(all_of(M7_4)) %>% 
  aggregate_and_document_scale()

data$M7_5 <- data %>% 
  select(all_of(M7_5)) %>% 
  aggregate_and_document_scale()

data$M7_6 <- data %>% 
  select(all_of(M7_6)) %>% 
  aggregate_and_document_scale()

data$M7_7 <- data %>% 
  select(all_of(M7_7)) %>% 
  aggregate_and_document_scale()
```

``` {R assumption}
## assumption check
random_variable <- rchisq(nrow(data), 7)
fake_model <- lm(random_variable ~ ., 
                 data = data[ , -c(86:91)])
standardized <- rstudent(fake_model)
fitvalues <- scale(fake_model$fitted.values)
plot(fake_model,2)#check for linearity
#We assume the the multivariate relationship between continuous variables is linear (i.e., no curved)
#There are many ways to test this, but we can use a QQ/PP Plot to examine for linearity

hist(standardized)#check for normality
#We expect that the residuals are normally distributed
#Not that the *sample* is normally distributed 
#Generally, SEM requires a large sample size, thus, buffering against normality deviations

{plot(standardized, fitvalues)
  abline(v = 0)
  abline(h = 0)
}#check for homogeneity + Homoscedasticity
#These assumptions are about equality of the variances
#We assume equal variances between groups for things like t-tests, ANOVA
#Here the assumption is equality in the spread of variance across predicted values 

##rename
data_cleaned <- data

#prepare dataframe for different scales
DGS <- data_cleaned[grep("DGS_1",colnames(data_cleaned)):grep("DGS_75",colnames(data_cleaned))]
DGS <- DGS[,-c(grep("DGS_31",colnames(DGS)),grep("DGS_53",colnames(DGS)))]

HEXACO_C <- data_cleaned[grep("HEXACO_C_1",colnames(data_cleaned)):grep("HEXACO_C_10",colnames(data_cleaned))]
```

###EFA

```{r EFA_all}
##descriptive analysis for all items
DGS_descriptive <- describe(DGS)
##EFA for DGS

#Kaiser Criterion
ev<- eigen(cor(DGS))
ev$values
sum(ev$values > 1)
sum(ev$values > .7)

#scree plot and parallel analysis
scree(DGS, pc=FALSE)
fa.parallel(DGS,
            fm="ml",
            fa="fa")
```


```{r EFA_9model}
DGS_fit_9 <- DGS %>%
  select(!c(DGS_3,DGS_4,DGS_12,DGS_14,DGS_16,DGS_25,DGS_40,DGS_43,DGS_34,DGS_50,DGS_59,DGS_62,DGS_66,DGS_37,DGS_42,DGS_23))

EFA_fit_9 <- fa(DGS_fit_9,
             nfactors = 9,
             rotate = "oblimin",
             fm="ml")
EFA_fit_9
print(EFA_fit_9$loadings, cutoff = 0.3)
print(EFA_fit_9$loadings)#model Abandoned because of conceptual reasons (see write-up)

```


```{r EFA_7model}
#7 factor (trim items with loading lower than 0.3)

DGS_fit_7 <- DGS %>%
  select(!c(DGS_16,DGS_40,DGS_43,DGS_50,DGS_42,DGS_23,DGS_14))

EFA_fit_7 <- fa(DGS_fit_7,
             nfactors = 7,
             rotate = "oblimin",
             fm="ml")
EFA_fit_7
print(EFA_fit_7$loadings, cutoff = 0.3)
print(EFA_fit_7$loadings)

##fit indices
EFA_fit_7$rms  # Root mean square of the residuals (lower the better)
EFA_fit_7$RMSEA # root mean squared error of approximation (lower the better)
EFA_fit_7$TLI  # tucker lewis index
1- ((EFA_fit_7$STATISTIC-EFA_fit_7$dof)/
      (EFA_fit_7$null.chisq-EFA_fit_7$null.dof))  #CFI

```


```{r EFA_7model_concise}
#7 factors concise model
DGS_fit_7C <- DGS %>%
  select(c(DGS_4,DGS_12,DGS_15,DGS_17,DGS_19,DGS_22,DGS_32,DGS_33,DGS_49,DGS_56,DGS_60,DGS_75,
           DGS_10,DGS_26,DGS_41,DGS_54,DGS_57,DGS_69,DGS_72,
           DGS_9,DGS_27,DGS_29,DGS_46,DGS_51,DGS_52,
           DGS_1,DGS_21,DGS_44,DGS_65,
           DGS_20,DGS_28,DGS_35,DGS_48,DGS_68,
           DGS_6,DGS_38,DGS_39,DGS_45,DGS_67,DGS_70,DGS_71,
           DGS_2,DGS_11))


EFA_fit_7C <- fa(DGS_fit_7C,
             nfactors = 7,
             rotate = "oblimin",
             fm="ml")
EFA_fit_7C
print(EFA_fit_7C$loadings, cutoff = 0.3)
print(EFA_fit_7C$loadings)

##fit indices
EFA_fit_7C$rms  # Root mean square of the residuals (lower the better)
EFA_fit_7C$RMSEA # root mean squared error of approximation (lower the better)
EFA_fit_7C$TLI  # tucker lewis index
1- ((EFA_fit_7C$STATISTIC-EFA_fit_7C$dof)/
      (EFA_fit_7C$null.chisq-EFA_fit_7C$null.dof))  #CFI

anova(EFA_fit_7,EFA_fit_7C)
```

```#{r 7model_trim}
#7 factors model triming
DGS_fit_7C <- DGS %>%
  select(c(DGS_4,DGS_12,DGS_15,DGS_17,DGS_19,DGS_22,DGS_32,DGS_33,DGS_49,DGS_56,DGS_60,DGS_75,
           DGS_10,DGS_26,DGS_41,DGS_54,DGS_57,DGS_69,DGS_72,
           DGS_9,DGS_27,DGS_29,DGS_46,DGS_51,DGS_52,
           DGS_1,DGS_21,DGS_44,DGS_65,
           DGS_20,DGS_28,DGS_35,DGS_68,
           DGS_6,DGS_39,DGS_45,DGS_67,DGS_70,
           DGS_2,DGS_11,DGS_48,DGS_13,DGS_73))
#trim 38,71because of the negative loading on factor 1
#trim 66 because of the low relevancy
#trim 44 because of the repetitiveness in description

EFA_fit_7C <- fa(DGS_fit_7C,
             nfactors = 7,
             rotate = "oblimin",
             fm="ml")
EFA_fit_7C
print(EFA_fit_7C$loadings, cutoff = 0.3)
print(EFA_fit_7C$loadings)

##fit indices
EFA_fit_7C$rms  # Root mean square of the residuals (lower the better)
EFA_fit_7C$RMSEA # root mean squared error of approximation (lower the better)
EFA_fit_7C$TLI  # tucker lewis index
1- ((EFA_fit_7C$STATISTIC-EFA_fit_7C$dof)/
      (EFA_fit_7C$null.chisq-EFA_fit_7C$null.dof))  #CFI

```

```{r 4_factors}
DGS_fit_4 <- DGS %>%
  select(!c(DGS_13,DGS_73))

#try 4 factors model
EFA_fit_4 <- fa(DGS_fit_4,
             nfactors = 4,
             rotate = "oblimin",
             fm="ml")
EFA_fit_4
print(EFA_fit_4$loadings, cutoff = 0.45)
print(EFA_fit_4$loadings)

#fit indices
EFA_fit_4$rms  # Root mean square of the residuals (lower the better)
EFA_fit_4$RMSEA # root mean squared error of approximation (lower the better)
EFA_fit_4$TLI  # tucker lewis index
1- ((EFA_fit_4$STATISTIC-EFA_fit_4$dof)/
      (EFA_fit_4$null.chisq-EFA_fit_4$null.dof))  #CFI

##abandon because the second factor is just the list of reverse coded items (poor conceptual fits)
```


```{r 6_factors}
# try to trim out behavioral items and create 6 factors
DGS_fit_6 <- DGS %>%
  select(!c(DGS_13,DGS_73,DGS_16,DGS_40,DGS_42,DGS_43))

EFA_fit_6 <- fa(DGS_fit_6,
             nfactors = 6,
             rotate = "oblimin",
             fm="ml")
EFA_fit_6
print(EFA_fit_6$loadings, cutoff = 0.4)
print(EFA_fit_6$loadings)

DGS_beh <- data%>%
  select(c(DGS_13,DGS_73))

EFA_fit_6$rms  # Root mean square of the residuals (lower the better)
EFA_fit_6$RMSEA # root mean squared error of approximation (lower the better)
EFA_fit_6$TLI  # tucker lewis index
1- ((EFA_fit_6$STATISTIC-EFA_fit_6$dof)/
      (EFA_fit_6$null.chisq-EFA_fit_6$null.dof))  #CFI

```


```{r 6_factors_concise}
# try to trim out behavioral items and create 6 factors
DGS_fit_6C <- DGS %>%
  select(c(
    DGS_4,DGS_12,DGS_15,DGS_17,DGS_18,DGS_19,DGS_22,DGS_30,DGS_32,DGS_33,DGS_34,DGS_36,DGS_37,DGS_49,DGS_57,DGS_58,DGS_60,DGS_61,DGS_63,DGS_74,DGS_75,
    DGS_5,DGS_10,DGS_26,DGS_41,DGS_54,DGS_69,DGS_72,
    DGS_9,DGS_20,DGS_27,DGS_29,DGS_46,DGS_52,
    DGS_2,DGS_11,DGS_28,DGS_35,DGS_48,DGS_68,
    DGS_1,DGS_21,DGS_44,DGS_65,
    DGS_6,DGS_38,DGS_39,DGS_45,DGS_67,DGS_70,DGS_71
  ))
# 64 59 47(poor conceptual fit) 55(mixed conceptual fit) 23(poor conceptual fit)
EFA_fit_6C <- fa(DGS_fit_6C,
             nfactors = 6,
             rotate = "oblimin",
             fm="ml")
EFA_fit_6C
print(EFA_fit_6C$loadings, cutoff = 0.3)
print(EFA_fit_6C$loadings)

#fit
EFA_fit_6C$rms  # Root mean square of the residuals (lower the better)
EFA_fit_6C$RMSEA # root mean squared error of approximation (lower the better)
EFA_fit_6C$TLI  # tucker lewis index
1- ((EFA_fit_6C$STATISTIC-EFA_fit_6C$dof)/
      (EFA_fit_6C$null.chisq-EFA_fit_6C$null.dof))  #CFI
```


###potential higher order model
```{r 3factors}
DGS_fit_3 <- DGS %>%
  select(c(
    DGS_4,DGS_12,DGS_15,DGS_17,DGS_18,DGS_19,DGS_22,DGS_30,DGS_32,DGS_33,DGS_34,DGS_36,DGS_37,DGS_49,DGS_57,DGS_58,DGS_60,DGS_61,DGS_63,DGS_74,DGS_75,
    DGS_5,DGS_10,DGS_26,DGS_41,DGS_54,DGS_69,DGS_72,
    DGS_9,DGS_20,DGS_27,DGS_29,DGS_46,DGS_52,
    DGS_2,DGS_11,DGS_28,DGS_35,DGS_48,DGS_68,
    DGS_1,DGS_21,DGS_44,DGS_65,
    DGS_6,DGS_38,DGS_39,DGS_45,DGS_67,DGS_70,DGS_71
  ))

EFA_fit_3 <- fa(DGS_fit_3,
             nfactors = 3,
             rotate = "oblimin",
             fm="ml")
EFA_fit_3
print(EFA_fit_3$loadings, cutoff = 0.3)
print(EFA_fit_3$loadings)

#fit
EFA_fit_3$rms  # Root mean square of the residuals (lower the better)
EFA_fit_3$RMSEA # root mean squared error of approximation (lower the better)
EFA_fit_3$TLI  # tucker lewis index
1- ((EFA_fit_3$STATISTIC-EFA_fit_3$dof)/
      (EFA_fit_3$null.chisq-EFA_fit_3$null.dof))  #CFI
```

```{r CFA_3factors}

DGS_3M_model <- '
S1 =~ DGS_4+DGS_12+DGS_15+DGS_17+DGS_18+DGS_19+DGS_22+DGS_30+DGS_32+DGS_33+DGS_34+DGS_36+DGS_37+DGS_49+DGS_57+DGS_58+DGS_60+DGS_61+DGS_63+DGS_74+DGS_74
S2 =~ DGS_5+DGS_10+DGS_26+DGS_41+DGS_54+DGS_69+DGS_72
S3 =~ DGS_9+DGS_20+DGS_27+DGS_29+DGS_46+DGS_52
S4 =~ DGS_2+DGS_11+DGS_28+DGS_35+DGS_48+DGS_68
S5 =~ DGS_1+DGS_21+DGS_44+DGS_65
S6 =~ DGS_6+DGS_38+DGS_39+DGS_45+DGS_67+DGS_70+DGS_71

F1 =~ S1 + S3
F2 =~ S2 + S5
F3 =~ S4 + S6
'

DGS_3M_fit <- cfa(
  model = DGS_3M_model,
  data = DGS,
  std.lv = TRUE)

summary(DGS_3M_fit,
        standardized = TRUE,
        rsquare = TRUE,
        fit.measures=TRUE)

parameterestimates(DGS_3M_fit,
                   standardized = TRUE)

fitmeasures(DGS_3M_fit)

modificationindices(DGS_3M_fit,sort = T)

semPaths(DGS_3M_fit,
         whatLabels = "std",
         what = "std",
         layout = "tree2",
         edge.label.cex = 1)

model_parameters(DGS_3M_fit, standardize = TRUE)
```



###lower structure exploration

```{r lower_structure_F1}

#select items for this factor
DGS_7M_f1 <- DGS%>%
  select(c(DGS_4,DGS_7,DGS_12,DGS_15,DGS_17,DGS_18,DGS_19,DGS_22,DGS_25,DGS_30,DGS_32,DGS_33,DGS_34,DGS_36,DGS_37,DGS_49,DGS_55,DGS_56,DGS_57,DGS_58,DGS_59,DGS_60,DGS_61,DGS_63,DGS_64,DGS_74,DGS_75))

#run for concise model
DGS_7M_f1 <- DGS%>%
  select(c(DGS_4,DGS_12,DGS_15,DGS_17,DGS_19,DGS_22,DGS_32,DGS_33,DGS_49,DGS_56,DGS_60,DGS_75))

cor.plot(DGS_7M_f1)

##Kaiser Criterion
ev<- eigen(cor(DGS_7M_f1))
ev$values
sum(ev$values > 1)
sum(ev$values > .7)

#scree plot and parallel analysis
scree(DGS_7M_f1, pc=FALSE)

fa.parallel(DGS_7M_f1,
            fm="ml",
            fa="fa")
#EFA
EFA_7M_f1 <- fa(DGS_7M_f1,
             nfactors = 3,
             rotate = "oblimin",
             fm="ml")
EFA_7M_f1
print(EFA_7M_f1$loadings, cutoff = 0.3)
print(EFA_7M_f1$loadings)           

#visualization

fa.diagram(EFA_7M_f1)
            
```


```{r lower_structure_F2}

#select items for this factor
DGS_7M_f2 <- DGS%>%
  select(c(DGS_3,DGS_5,DGS_8,DGS_10,DGS_15,DGS_26,DGS_33,DGS_41,DGS_44,DGS_45,DGS_47,DGS_54,DGS_57,DGS_58,DGS_69,DGS_72,DGS_74))
#run for concise model
DGS_7M_f2 <- DGS%>%
  select(c(DGS_10,DGS_26,DGS_41,DGS_54,DGS_57,DGS_69,DGS_72))

cor.plot(DGS_7M_f2)

##Kaiser Criterion
ev<- eigen(cor(DGS_7M_f2))
ev$values
sum(ev$values > 1)
sum(ev$values > .7)

#scree plot and parallel analysis
scree(DGS_7M_f2, pc=FALSE)

fa.parallel(DGS_7M_f2,
            fm="ml",
            fa="fa")
#EFA
EFA_7M_f2 <- fa(DGS_7M_f2,
             nfactors = 1,
             rotate = "oblimin",
             fm="ml")
EFA_7M_f2
print(EFA_7M_f2$loadings, cutoff = 0.3)
print(EFA_7M_f2$loadings)           

#visualization
fa.plot(EFA_7M_f2,
  labels = colnames(DGS_7M_f2)
)

fa.diagram(EFA_7M_f2)
            
```

```{r lower_structure_F3}

#select items for this factor
DGS_7M_f3 <- DGS%>%
  select(c(DGS_9,DGS_27,DGS_29,DGS_46,DGS_51,DGS_52))

#run for concise model
DGS_7M_f3 <- DGS%>%
   select(c(DGS_9,DGS_27,DGS_29,DGS_46,DGS_51,DGS_52))

cor.plot(DGS_7M_f3)

##Kaiser Criterion
ev<- eigen(cor(DGS_7M_f3))
ev$values
sum(ev$values > 1)
sum(ev$values > .7)

#scree plot and parallel analysis
scree(DGS_7M_f3, pc=FALSE)

fa.parallel(DGS_7M_f3,
            fm="ml",
            fa="fa")
#EFA
EFA_7M_f3 <- fa(DGS_7M_f3,
             nfactors = 2,
             rotate = "oblimin",
             fm="ml")
EFA_7M_f3
print(EFA_7M_f3$loadings, cutoff = 0.3) 

EFA_7M_f3 <- fa(DGS_7M_f3,
             nfactors = 1,
             rotate = "oblimin",
             fm="ml")
EFA_7M_f3
print(EFA_7M_f3$loadings, cutoff = 0.3) 
#recommend 1 factor because 2 factors basically separate negative and positive code items.

#visualization
fa.diagram(EFA_7M_f3)
            
```

```{r lower_structure_F4}

#select items for this factor
DGS_7M_f4 <- DGS%>%
  select(c(DGS_1,DGS_21,DGS_44,DGS_63,DGS_65)) #remove 69 due to low loading in the 7 factor model and low conceptual relevancy.

##Kaiser Criterion
ev<- eigen(cor(DGS_7M_f4))
ev$values
sum(ev$values > 1)
sum(ev$values > .7)

#scree plot and parallel analysis
scree(DGS_7M_f4, pc=FALSE)

fa.parallel(DGS_7M_f4,
            fm="ml",
            fa="fa")
#EFA
EFA_7M_f4 <- fa(DGS_7M_f4,
             nfactors = 2,
             rotate = "oblimin",
             fm="ml")
EFA_7M_f4
print(EFA_7M_f4$loadings, cutoff = 0.3) 
#recommend 1 factor becuase these basically separate the negative and positive coded items. 

#visualization
fa.diagram(EFA_7M_f4)

#run for concise model
DGS_7M_f4 <- DGS%>%
   select(c(DGS_1,DGS_21,DGS_44,DGS_65))#recommend 1 factor for the concise version

cor.plot(DGS_7M_f4)

##Kaiser Criterion
ev<- eigen(cor(DGS_7M_f4))
ev$values
sum(ev$values > 1)
sum(ev$values > .7)

#scree plot and parallel analysis
scree(DGS_7M_f4, pc=FALSE)

fa.parallel(DGS_7M_f4,
            fm="ml",
            fa="fa")
#EFA
EFA_7M_f4 <- fa(DGS_7M_f4,
             nfactors = 1,
             rotate = "oblimin",
             fm="ml")
EFA_7M_f4
print(EFA_7M_f4$loadings, cutoff = 0.3) 
#recommend 1 factor 

#visualization
fa.diagram(EFA_7M_f4)
            
```

```{r lower_structure_F5}

#select items for this factor
DGS_7M_f5 <- DGS%>%
  select(c(DGS_20,DGS_24,DGS_28,DGS_35,DGS_48,DGS_64,DGS_68)) #remove 47 due to low loading in the 7 factor model and low conceptual relevancy.

#run for concise model
DGS_7M_f5 <- DGS%>%
   select(c(DGS_20,DGS_28,DGS_35,DGS_48,DGS_68)) # recommend one factor for the concise version

cor.plot(DGS_7M_f5)

##Kaiser Criterion
ev<- eigen(cor(DGS_7M_f5))
ev$values
sum(ev$values > 1)
sum(ev$values > .7)

#scree plot and parallel analysis
scree(DGS_7M_f5, pc=FALSE)

fa.parallel(DGS_7M_f5,
            fm="ml",
            fa="fa")
#EFA
EFA_7M_f5 <- fa(DGS_7M_f5,
             nfactors = 2,
             rotate = "oblimin",
             fm="ml")
EFA_7M_f5
print(EFA_7M_f5$loadings, cutoff = 0.3) 
#2 factors model looks good. It seperate cognitive and affective components

#visualization
fa.diagram(EFA_7M_f5)
            
```

```{r lower_structure_F6}

#select items for this factor
DGS_7M_f6 <- DGS%>%
  select(c(DGS_6,DGS_18,DGS_38,DGS_39,DGS_45,DGS_55,DGS_67,DGS_70,DGS_71)) #remove 62 due to low loading in the 7 factor model and low conceptual relevancy.

#run for concise model
DGS_7M_f6 <- DGS%>%
   select(c(DGS_6,DGS_38,DGS_39,DGS_45,DGS_67,DGS_70,DGS_71)) # need further inspection

cor.plot(DGS_7M_f6)

##Kaiser Criterion
ev<- eigen(cor(DGS_7M_f6))
ev$values
sum(ev$values > 1)
sum(ev$values > .7)

#scree plot and parallel analysis
scree(DGS_7M_f6, pc=FALSE)

fa.parallel(DGS_7M_f6,
            fm="ml",
            fa="fa")
#EFA
EFA_7M_f6 <- fa(DGS_7M_f6,
             nfactors = 3,
             rotate = "oblimin",
             fm="ml")
EFA_7M_f6 
print(EFA_7M_f6 $loadings, cutoff = 0.3) 

EFA_7M_f6 <- fa(DGS_7M_f6,
             nfactors = 2,
             rotate = "oblimin",
             fm="ml")
EFA_7M_f6 
print(EFA_7M_f6 $loadings, cutoff = 0.3)

##need to check 38 and 71 and see if they fit the model. IRT may be helpful here.
DGS%>%
  ggplot()+
  geom_bar(aes(x=DGS_38, alpha = 0.1))+
  geom_bar(aes(x=DGS_67))
#visualization
fa.diagram(EFA_7M_f6)
            
```

```{r lower_structure_F7}

#select items for this factor
DGS_7M_f7 <- DGS%>%
  select(c(DGS_2,DGS_5,DGS_11,DGS_13,DGS_48,DGS_66,DGS_73)) #remove 47 due to low loading in the 7 factor model and low conceptual relevancy.

#run for concise model
DGS_7M_f7 <- DGS%>%
   select(c(DGS_2,DGS_11,DGS_13,DGS_73)) # recommend one factor for the concise version

cor.plot(DGS_7M_f7)

##Kaiser Criterion
ev<- eigen(cor(DGS_7M_f7))
ev$values
sum(ev$values > 1)
sum(ev$values > .7)

#scree plot and parallel analysis
scree(DGS_7M_f7, pc=FALSE)

fa.parallel(DGS_7M_f7,
            fm="ml",
            fa="fa")
#EFA
EFA_7M_f7 <- fa(DGS_7M_f7,
             nfactors = 1,
             rotate = "oblimin",
             fm="ml")
EFA_7M_f7
print(EFA_7M_f7$loadings, cutoff = 0.3) 

#visualization
fa.diagram(EFA_7M_f7)
            
```


###Confirmatory factor analysis

```#{r CFA}

DGS_7M_model <- '
F1 =~ DGS_4+DGS_7+DGS_12+DGS_15+DGS_17+DGS_18+DGS_19+DGS_22+DGS_25+DGS_30+DGS_32+DGS_33+DGS_34+DGS_36+DGS_37+DGS_49+DGS_55+DGS_56+DGS_57+DGS_58+DGS_59+DGS_60+DGS_61+DGS_63+DGS_64+DGS_74+DGS_75
F2 =~ DGS_3+DGS_5+DGS_8+DGS_10+DGS_15+DGS_26+DGS_33+DGS_41+DGS_44+DGS_45+DGS_47+DGS_54+DGS_57+DGS_58+DGS_69+DGS_72+DGS_74
F3 =~ DGS_9+DGS_27+DGS_29+DGS_46+DGS_51+DGS_52
F4 =~ DGS_1+DGS_21+DGS_44+DGS_63+DGS_65
F5 =~ DGS_20+DGS_24+DGS_28+DGS_35+DGS_48+DGS_64+DGS_68
F6 =~ DGS_6+DGS_18+DGS_38+DGS_39+DGS_45+DGS_55+DGS_67+DGS_70+DGS_71
F7 =~ DGS_2+DGS_5+DGS_11+DGS_13+DGS_48+DGS_66+DGS_73
'

DGS_7M_fit <- cfa(
  model = DGS_7M_model,
  data = DGS,
  std.lv = TRUE)

summary(DGS_7M_fit,
        standardized = TRUE,
        rsquare = TRUE,
        fit.measures=TRUE)

parameterestimates(DGS_7M_fit,
                   standardized = TRUE)

fitmeasures(DGS_7M_fit)

modificationindices(DGS_7M_fit,sort = T)

semPaths(DGS_7M_fit,
         whatLabels = "std",
         what = "std",
         layout = "tree2",
         edge.label.cex = 1)

model_parameters(DGS_7M_fit, standardize = TRUE)

```


```#{r CFA_M7_concise}

DGS_7M_C_model <- '
F1=~DGS_4+DGS_12+DGS_15+DGS_17+DGS_19+DGS_22+DGS_32+DGS_33+DGS_49+DGS_56+DGS_60+DGS_75
F2=~DGS_10+DGS_26+DGS_41+DGS_54+DGS_57+DGS_69+DGS_72
F3=~DGS_9+DGS_27+DGS_29+DGS_46+DGS_51+DGS_52
F4=~DGS_1+DGS_21+DGS_44+DGS_65
F5=~DGS_20+DGS_28+DGS_35+DGS_48+DGS_68
F6=~DGS_6+DGS_38+DGS_39+DGS_45+DGS_67+DGS_70+DGS_71
F7=~DGS_2+DGS_11+DGS_48+DGS_13
'

DGS_7M_C_fit <- cfa(
  model = DGS_7M_C_model,
  data = DGS,
  std.lv = TRUE)

summary(DGS_7M_C_fit,
        standardized = TRUE,
        rsquare = TRUE,
        fit.measures=TRUE)

parameterestimates(DGS_7M_C_fit,
                   standardized = TRUE)

fitmeasures(DGS_7M_C_fit)

modificationindices(DGS_7M_C_fit,sort = T)

semPaths(DGS_7M_C_fit,
         whatLabels = "std",
         what = "std",
         layout = "tree2",
         edge.label.cex = 1)

model_parameters(DGS_7M_C_fit, standardize = TRUE)

tidy(DGS_7M_C_fit) #with corvar compared to the latter one
glance(DGS_7M_C_fit)  # fit indices in a glance

#compare model: anova(model1,model2)
#check fitmeasures(model, c("aic","evic"))
```


###Item assignment

```{r scale_assign}
DGS_7model_1 <- DGS %>%
  select(c(DGS_4,DGS_12,DGS_15,DGS_17,DGS_19,DGS_22,DGS_32,DGS_33,DGS_49,DGS_56,DGS_60,DGS_75))
DGS_7model_2 <- DGS %>%
  select(c(DGS_5,DGS_10,DGS_26,DGS_41,DGS_54,DGS_69,DGS_72))
DGS_7model_3 <- DGS %>%
  select(c(DGS_9, DGS_27,DGS_29,DGS_46,DGS_51,DGS_52))
DGS_7model_4 <- DGS %>%
  select(c(DGS_1,DGS_21,DGS_44,DGS_65))
DGS_7model_5 <- DGS %>%
  select(c(DGS_20,DGS_28,DGS_35,DGS_48,DGS_68))
DGS_7model_6 <- DGS %>%
  select(c(DGS_6,DGS_38,DGS_39,DGS_45,DGS_67,DGS_70,DGS_71))
DGS_7model_7 <- DGS %>%
  select(c(DGS_2,DGS_11,DGS_73,DGS_13))

#6 factors model without behavioral items
DGS_6model_1 <- DGS %>%
  select(c(DGS_4,DGS_12,DGS_15,DGS_17,DGS_18,DGS_19,DGS_22,DGS_30,DGS_32,DGS_33,DGS_34,DGS_36,DGS_37,DGS_49,DGS_57,DGS_58,DGS_60,DGS_61,DGS_63,DGS_74,DGS_75))
DGS_6model_2 <- DGS %>%
  select(c(DGS_5,DGS_10,DGS_26,DGS_41,DGS_54,DGS_69,DGS_72))
DGS_6model_3 <- DGS %>%
  select(c(DGS_9,DGS_20,DGS_27,DGS_29,DGS_46,DGS_52))
DGS_6model_4 <- DGS %>%
  select(c(DGS_2,DGS_11,DGS_28,DGS_35,DGS_48,DGS_68))
DGS_6model_5 <- DGS %>%
  select(c(DGS_1,DGS_21,DGS_44,DGS_65))
DGS_6model_6 <- DGS %>%
  select(c(DGS_6,DGS_38,DGS_39,DGS_45,DGS_67,DGS_70,DGS_71))

```

##corplot

```{r corplots}
#visualization
corPlot(DGS_7model_1)
corPlot(DGS_7model_2)
corPlot(DGS_7model_3)
corPlot(DGS_7model_4)
corPlot(DGS_7model_5)
corPlot(DGS_7model_6)
corPlot(DGS_7model_7)
cor(DGS_beh)

# 6 factors
corPlot(DGS_6model_1)
corPlot(DGS_6model_2)
corPlot(DGS_6model_3)
corPlot(DGS_6model_4)
corPlot(DGS_6model_5)
corPlot(DGS_6model_6)

## make a correlation matrix to screen for overlapping items
```


###IRT! (generalized partial credit model)

## 7 factors model

```{R IRT7_1}
DGS_IRT_1 = mirt(data = DGS_7model_1,
      model = 1, #this is for one factor
      itemtype = "gpcmIRT" #generalized partial credit model
)
summary(DGS_IRT_1)
coef(DGS_IRT_1, IRTpars = T)
#itemplot(DGS_IRT_1, 1, type = "trace")
itemplot(DGS_IRT_1, 1, type = "info")
plot(DGS_IRT_1, type = "trace")
plot(DGS_IRT_1, type = "info")
plot(DGS_IRT_1) #expected score curve
#person fit
#fscores(DGS_IRT_1) #factor score for each participants
#mirt::itemfit(DGS_IRT_1)
#mirt::personfit(DGS_IRT_1)


```


```{R IRT7_2}

DGS_IRT_2 = mirt(data = DGS_7model_2,
      model = 1, #this is for one factor
      itemtype = "gpcmIRT" #generalized partial credit model
)
summary(DGS_IRT_2)
coef(DGS_IRT_2, IRTpars = T)
#itemplot(DGS_IRT_2, 5, type = "trace")
itemplot(DGS_IRT_2, 5, type = "info")
plot(DGS_IRT_2, type = "trace")
plot(DGS_IRT_2, type = "info")
plot(DGS_IRT_2) #expected score curve
#person fit
#fscores(DGS_IRT_2) #factor score for each participants
#mirt::itemfit(DGS_IRT_2)
#mirt::personfit(DGS_IRT_2)

```


```{R IRT7_3}

DGS_IRT_3 = mirt(data = DGS_7model_3,
      model = 1, #this is for one factor
      itemtype = "gpcmIRT" #generalized partial credit model
)
summary(DGS_IRT_3)
coef(DGS_IRT_3, IRTpars = T)
#itemplot(DGS_IRT_3, 1, type = "trace")
itemplot(DGS_IRT_3, 3, type = "info")
plot(DGS_IRT_3, type = "trace")
plot(DGS_IRT_3, type = "info")
plot(DGS_IRT_3) #expected score curve
#person fit
#fscores(DGS_IRT_3) #factor score for each participants
#mirt::itemfit(DGS_IRT_3)
#mirt::personfit(DGS_IRT_3)
```

```{r IRT7_4}

DGS_IRT_4 = mirt(data = DGS_7model_4,
      model = 1, #this is for one factor
      itemtype = "gpcmIRT" #generalized partial credit model
)
summary(DGS_IRT_4)
coef(DGS_IRT_4, IRTpars = T)
#itemplot(DGS_IRT_4, 5, type = "trace")
itemplot(DGS_IRT_4, 4, type = "info")
plot(DGS_IRT_4, type = "trace")
plot(DGS_IRT_4, type = "info")
plot(DGS_IRT_4) #expected score curve
#person fit
#fscores(DGS_IRT_4) #factor score for each participants
#mirt::itemfit(DGS_IRT_4)
#mirt::personfit(DGS_IRT_4)

```

```{r IRT7_5}

DGS_IRT_5 = mirt(data = DGS_7model_5,
      model = 1, #this is for one factor
      itemtype = "gpcmIRT" #generalized partial credit model
)
summary(DGS_IRT_5)
coef(DGS_IRT_5, IRTpars = T)
#itemplot(DGS_IRT_5, 5, type = "trace")
itemplot(DGS_IRT_5, 3, type = "info")
plot(DGS_IRT_5, type = "trace")
plot(DGS_IRT_5, type = "info")
plot(DGS_IRT_5) #expected score curve
#person fit
#fscores(DGS_IRT_5) #factor score for each participants
#mirt::itemfit(DGS_IRT_5)
#mirt::personfit(DGS_IRT_5)

```

```{r IRT7_6}


DGS_IRT_6 = mirt(data = DGS_7model_6,
      model = 1, #this is for one factor
      itemtype = "gpcmIRT" #generalized partial credit model
)
summary(DGS_IRT_6)
coef(DGS_IRT_6, IRTpars = T)
#itemplot(DGS_IRT_6, 5, type = "trace")
itemplot(DGS_IRT_6, 1, type = "info")
plot(DGS_IRT_6, type = "trace")
plot(DGS_IRT_6, type = "info")
plot(DGS_IRT_6) #expected score curve
#person fit
#fscores(DGS_IRT_6) #factor score for each participants
#mirt::itemfit(DGS_IRT_6)
#mirt::personfit(DGS_IRT_6)

```

```{r IRT7_7}

DGS_IRT_7 = mirt(data = DGS_7model_7,
      model = 1, #this is for one factor
      itemtype = "gpcmIRT" #generalized partial credit model
)
summary(DGS_IRT_7)
coef(DGS_IRT_7, IRTpars = T)
#itemplot(DGS_IRT_7, 1, type = "trace")
itemplot(DGS_IRT_7, 1, type = "info")
plot(DGS_IRT_7, type = "trace")
plot(DGS_IRT_7, type = "info")
plot(DGS_IRT_7) #expected score curve
#person fit
#fscores(DGS_IRT_7) #factor score for each participants
#mirt::itemfit(DGS_IRT_7)
#mirt::personfit(DGS_IRT_7)
```


## 6 factors (dropping rule is loading in IFA < 0.3)
```{r IRT}
DGS_IRT6 = mirt(data = DGS_fit_6C,
      model = 1, #this is for one factor
      itemtype = "gpcmIRT" #generalized partial credit model
)
summary(DGS_IRT6)
plot(DGS_IRT6, type = "info")
plot(DGS_IRT6, type = "trace")


```


```{R IRT6_1}
DGS_IRT6_1 = mirt(data = DGS_6model_1,
      model = 1, #this is for one factor
      itemtype = "gpcmIRT" #generalized partial credit model
)
summary(DGS_IRT6_1)
coef(DGS_IRT6_1, IRTpars = T)
#itemplot(DGS_IRT6_1, 1, type = "trace")
itemplot(DGS_IRT6_1, 1, type = "info")
plot(DGS_IRT6_1, type = "trace")
plot(DGS_IRT6_1, type = "info")
plot(DGS_IRT6_1) #expected score curve


##recommend taking out 4 and 22
DGS_6model_1 <- DGS_6model_1%>%
  select(!c(DGS_4,DGS_22))

DGS_IRT6_1 = mirt(data = DGS_6model_1,
      model = 1, #this is for one factor
      itemtype = "gpcmIRT" #generalized partial credit model
)
summary(DGS_IRT6_1)
plot(DGS_IRT6_1, type = "trace")
#traces suggest that 2-4 options were not commonly used
plot(DGS_IRT6_1, type = "info")
#item information suggests that we need to improve the ability to identify people on top of the altruism scores. 


#person fit
#fscores(DGS_IRT6_1) #factor score for each participants
#mirt::itemfit(DGS_IRT6_1)
#mirt::personfit(DGS_IRT6_1)
```

```{R IRT6_2}
DGS_IRT6_2 = mirt(data = DGS_6model_2,
      model = 1, #this is for one factor
      itemtype = "gpcmIRT" #generalized partial credit model
)
summary(DGS_IRT6_2)
coef(DGS_IRT6_2, IRTpars = T)
#itemplot(DGS_IRT6_2, 1, type = "trace")
itemplot(DGS_IRT6_2, 1, type = "info")
plot(DGS_IRT6_2, type = "trace")
plot(DGS_IRT6_2, type = "info")
plot(DGS_IRT6_2) #expected score curve

#person fit
#fscores(DGS_IRT6_2) #factor score for each participants
#mirt::itemfit(DGS_IRT6_2)
#mirt::personfit(DGS_IRT6_2)

```

```{R IRT6_3}
DGS_IRT6_3 = mirt(data = DGS_6model_3,
      model = 1, #this is for one factor
      itemtype = "gpcmIRT" #generalized partial credit model
)
summary(DGS_IRT6_3)
coef(DGS_IRT6_3, IRTpars = T)
#itemplot(DGS_IRT6_3, 1, type = "trace")
itemplot(DGS_IRT6_3, 1, type = "info")
plot(DGS_IRT6_3, type = "trace")
plot(DGS_IRT6_3, type = "info")
plot(DGS_IRT6_3) #expected score curve

# suggest remove 20
DGS_6model_3 <- DGS_6model_3%>%
  select(!c(DGS_20))
DGS_IRT6_3 = mirt(data = DGS_6model_3,
      model = 1, #this is for one factor
      itemtype = "gpcmIRT" #generalized partial credit model
)
summary(DGS_IRT6_3)

#person fit
#fscores(DGS_IRT6_3) #factor score for each participants
#mirt::itemfit(DGS_IRT6_3)
#mirt::personfit(DGS_IRT6_3)
```

```{R IRT6_4}
DGS_IRT6_4 = mirt(data = DGS_6model_4,
      model = 1, #this is for one factor
      itemtype = "gpcmIRT" #generalized partial credit model
)
summary(DGS_IRT6_4)
coef(DGS_IRT6_4, IRTpars = T)
#itemplot(DGS_IRT6_4, 1, type = "trace")
itemplot(DGS_IRT6_4, 1, type = "info")
plot(DGS_IRT6_4, type = "trace")
plot(DGS_IRT6_4, type = "info")
plot(DGS_IRT6_4) #expected score curve

#suggest remove 2, 11 due to poor discrimination
DGS_6model_4 <- DGS_6model_4 %>%
  select(!c(DGS_2,DGS_11))
DGS_IRT6_4 = mirt(data = DGS_6model_4,
      model = 1, #this is for one factor
      itemtype = "gpcmIRT" #generalized partial credit model
)
summary(DGS_IRT6_4)

#person fit
#fscores(DGS_IRT6_4) #factor score for each participants
#mirt::itemfit(DGS_IRT6_4)
#mirt::personfit(DGS_IRT6_4)

```

```{R IRT6_5}
DGS_IRT6_5 = mirt(data = DGS_6model_5,
      model = 1, #this is for one factor
      itemtype = "gpcmIRT" #generalized partial credit model
)
summary(DGS_IRT6_5)
coef(DGS_IRT6_5, IRTpars = T)
#itemplot(DGS_IRT6_5, 1, type = "trace")
itemplot(DGS_IRT6_5, 1, type = "info")
plot(DGS_IRT6_5, type = "trace")
plot(DGS_IRT6_5, type = "info")
plot(DGS_IRT6_5) #expected score curve

#suggest dropping 1
DGS_6model_5 <- DGS_6model_5 %>%
  select(!c(DGS_1))
DGS_IRT6_5 = mirt(data = DGS_6model_5,
      model = 1, #this is for one factor
      itemtype = "gpcmIRT" #generalized partial credit model
)
summary(DGS_IRT6_5)


#person fit
#fscores(DGS_IRT6_5) #factor score for each participants
#mirt::itemfit(DGS_IRT6_5)
#mirt::personfit(DGS_IRT6_5)

```

```{R IRT6_6}
DGS_IRT6_6 = mirt(data = DGS_6model_6,
      model = 1, #this is for one factor
      itemtype = "gpcmIRT" #generalized partial credit model
)
summary(DGS_IRT6_6)
coef(DGS_IRT6_6, IRTpars = T)
#itemplot(DGS_IRT6_6, 1, type = "trace")
itemplot(DGS_IRT6_6, 1, type = "info")
plot(DGS_IRT6_6, type = "trace")
plot(DGS_IRT6_6, type = "info")
plot(DGS_IRT6_6) #expected score curve

#suggest dropping 45
DGS_6model_6 <- DGS_6model_6 %>%
  select(!c(DGS_45))
DGS_IRT6_6 = mirt(data = DGS_6model_6,
      model = 1, #this is for one factor
      itemtype = "gpcmIRT" #generalized partial credit model
)
summary(DGS_IRT6_6)
#need some thoughts and modification here. The categorical imperative items are not lumping very well together. 

#person fit
#fscores(DGS_IRT6_6) #factor score for each participants
#mirt::itemfit(DGS_IRT6_6)
#mirt::personfit(DGS_IRT6_6)

```

```{r IRT_beh}
DGS_IRT_beh = mirt(data = DGS_beh,
      model = 1, #this is for one factor
      itemtype = "gpcmIRT" #generalized partial credit model
)
summary(DGS_IRT_beh)
coef(DGS_IRT_beh, IRTpars = T)
plot(DGS_IRT_beh, type = "trace")
plot(DGS_IRT_beh, type = "info")
plot(DGS_IRT_beh) #expected score curve
#person fit
fscores(DGS_IRT_beh) #factor score for each participants
mirt::itemfit(DGS_IRT_beh)
mirt::personfit(DGS_IRT_beh)
```

##trimming based on IRT

```{r IRT_trim}
#6 factors model without behavioral items
DGS_6model_1 <- DGS %>%
  select(c(DGS_12,DGS_15,DGS_17,DGS_18,DGS_19,DGS_30,DGS_32,DGS_33,DGS_34,DGS_36,DGS_37,DGS_49,DGS_57,DGS_58,DGS_60,DGS_61,DGS_63,DGS_74,DGS_74))
DGS_6model_2 <- DGS %>%
  select(c(DGS_5,DGS_10,DGS_26,DGS_41,DGS_54,DGS_69,DGS_72))
DGS_6model_3 <- DGS %>%
  select(c(DGS_9,DGS_27,DGS_29,DGS_46,DGS_52))
DGS_6model_4 <- DGS %>%
  select(c(DGS_28,DGS_35,DGS_48,DGS_68))
DGS_6model_5 <- DGS %>%
  select(c(DGS_21,DGS_44,DGS_65))
DGS_6model_6 <- DGS %>%
  select(c(DGS_6,DGS_38,DGS_39,DGS_67,DGS_70,DGS_71))
```

##check factor structure after trimming
```{r 6factors_trimmed}
# try to trim out behavioral items and create 6 factors
DGS_fit_6C <- DGS %>%
  select(c(
    DGS_12,DGS_15,DGS_17,DGS_18,DGS_19,DGS_30,DGS_32,DGS_33,DGS_34,DGS_36,DGS_37,DGS_49,DGS_57,DGS_58,DGS_60,DGS_61,DGS_63,DGS_74,DGS_75,
    DGS_5,DGS_10,DGS_26,DGS_41,DGS_54,DGS_69,DGS_72,
    DGS_9,DGS_27,DGS_29,DGS_46,DGS_52,
    DGS_28,DGS_35,DGS_48,DGS_68,
    DGS_21,DGS_44,DGS_65,
    DGS_6,DGS_38,DGS_39,DGS_67,DGS_70,DGS_71
  ))

EFA_fit_6C <- fa(DGS_fit_6C,
             nfactors = 6,
             rotate = "oblimin",
             fm="ml")
EFA_fit_6C
print(EFA_fit_6C$loadings, cutoff = 0.3)
print(EFA_fit_6C$loadings)

#fit
EFA_fit_6C$rms  # Root mean square of the residuals (lower the better)
EFA_fit_6C$RMSEA # root mean squared error of approximation (lower the better)
EFA_fit_6C$TLI  # tucker lewis index
1- ((EFA_fit_6C$STATISTIC-EFA_fit_6C$dof)/
      (EFA_fit_6C$null.chisq-EFA_fit_6C$null.dof))  #CFI

```
###likert visualization

```{r likert}
visu_likert <- function(x){
  x <- as.data.frame(lapply(x,factor))
  likert_x <- likert(x)
  likert_fit_x <- likert.bar.plot(likert_x)
  plot(likert_fit_x)
}

visu_likert(DGS_6model_1)
visu_likert(DGS_6model_2)
visu_likert(DGS_6model_3)
visu_likert(DGS_6model_4)
visu_likert(DGS_6model_5)
visu_likert(DGS_6model_6)

```

###scoring


```{r basic_score}
data$DGS_7C_1 <- rowSums(DGS_7model_1)/ncol(DGS_7model_1)
data$DGS_7C_2 <- rowSums(DGS_7model_2)/ncol(DGS_7model_2)
data$DGS_7C_3 <- rowSums(DGS_7model_3)/ncol(DGS_7model_3)
data$DGS_7C_4 <- rowSums(DGS_7model_4)/ncol(DGS_7model_4)
data$DGS_7C_5 <- rowSums(DGS_7model_5)/ncol(DGS_7model_5)
data$DGS_7C_6 <- rowSums(DGS_7model_6)/ncol(DGS_7model_6)
data$DGS_7C_7 <- rowSums(DGS_7model_7)/ncol(DGS_7model_7)

data$DGS_6C_1 <- rowSums(DGS_6model_1)/ncol(DGS_6model_1)
data$DGS_6C_2 <- rowSums(DGS_6model_2)/ncol(DGS_6model_2)
data$DGS_6C_3 <- rowSums(DGS_6model_3)/ncol(DGS_6model_3)
data$DGS_6C_4 <- rowSums(DGS_6model_4)/ncol(DGS_6model_4)
data$DGS_6C_5 <- rowSums(DGS_6model_5)/ncol(DGS_6model_5)
data$DGS_6C_6 <- rowSums(DGS_6model_6)/ncol(DGS_6model_6)

```

```{r beh}
#construct behavioral estimates

DGS_beh <- data%>%
  select(c(DGS_13,DGS_73))

data$DGS_beh <- rowSums(DGS_beh)/ncol(DGS_beh)

data$DGS_donation <- data %>%
  select(DGS_13)

data$DGS_vol <- data %>%
  select(DGS_73)
```

```{r IRT_score}

data$DGS_7C_1_fscore <- fscores(DGS_IRT_1)
data$DGS_7C_2_fscore <- fscores(DGS_IRT_2)
data$DGS_7C_3_fscore <- fscores(DGS_IRT_3)
data$DGS_7C_4_fscore <- fscores(DGS_IRT_4)
data$DGS_7C_5_fscore <- fscores(DGS_IRT_5)
data$DGS_7C_6_fscore <- fscores(DGS_IRT_6)
data$DGS_7C_7_fscore <- fscores(DGS_IRT_7)
```
###inferential analysis

```{r analysis}
psych::omega(HEXACO_C, nfactors = 4) # alpha = 0.82

DGS_HEXACO <- data %>%
  select(c(HEXACO_C,starts_with("DGS_7C_")))

cor.plot(DGS_HEXACO)

##regression to use non-behavioral to predict behaviors
data$DGS_beh <- rowSums(DGS_beh)/ncol(DGS_beh)

DGS_beh <- data %>%
  select(c(DGS_beh,
           DGS_7C_1,
           DGS_7C_2,
           DGS_7C_3,
           DGS_7C_4,
           DGS_7C_5,
           DGS_7C_6))

cor.plot(DGS_beh)


##with factor scores
DGSf_HEXACO <- data %>%
  select(c(HEXACO_C,starts_with("DGS_6C_"),DGS_donation,DGS_vol))
data$DGS_donation <- apply(data$DGS_donation, 2, as.numeric)
data$DGS_vol <- apply(data$DGS_vol, 2, as.numeric)

cor.plot(DGSf_HEXACO)


m_DGS_beh <- lm (
  DGS_donation ~ 
    DGS_6C_1 +
    DGS_6C_2 +
    DGS_6C_4 +
    DGS_6C_3 +
    DGS_6C_5 +
    DGS_6C_6,
  data= data
)
summary(m_DGS_beh)

m_DGS_beh <- lm (
  DGS_vol ~ 
    DGS_6C_1 +
    DGS_6C_2 +
    DGS_6C_4 +
    DGS_6C_3 +
    DGS_6C_5 +
    DGS_6C_6,
  data= data
)
summary(m_DGS_beh)
```