---
title: "DGS_S1_codebook"
author: "Qilin Zhang"
date: "2023-03-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(summarytools)
library(tidyverse) #data wrangling
library(codebook) #codebook generation
library(future) #reliability
library(ufs) #reliability
library(GGally) #reliability
library(GPArotation) #reliability
library(rio) #reading in different file types
library(labelled) #labeling data
```


## Cleaning

```{r cleaning_code, include = FALSE}

## use other read functions as appropriate for file type

dict <- rio::import(file = "data/DGS_S1_dictionary.xlsx") #dictionary

data <- read.csv(file = 'data/DGS_S1_Deidentified For Analyses.csv', sep = ",") #data

data <- data[-c(1:2),-c(1:7)]

## Variable types 
names <- dict %>% 
  filter(type == "character") %>% 
  pull(variable)
data[,names] <- 
  lapply(data[,names], as.character)

names <- dict %>% 
  filter(type == "factor") %>% 
  pull(variable)
data[,names] <- 
  lapply(data[,names], as.numeric) #factor variables are coded as numeric for codebook purposes

names <- dict %>% 
  filter(type == "numeric") %>% 
  pull(variable)
data[,names] <- 
  lapply(data[,names], as.numeric)

rm(names)

##data completion check and imputation

#remove failed attention check -55 participants from this process
data <- data %>%
  filter(DGS_31 == 4) %>%
  filter((DGS_53 == 2))


#function for checking percentage of missing data (unit=%)
percent_missing <- function(x){
  sum(is.na((x))/length(x)*100)
}
missing_R <- apply(data,1,percent_missing)
table(missing_R)

#use if don't want imputation(turn off if I need imputation)
replace_rows <- subset(data, missing_R<=0)
data <- replace_rows
```

```{r imputation, include= FALSE}
if(FALSE){
#subset based on filtering criteria
replace_rows <- subset(data, missing_R<=10)
no_rows <- subset(data, missing_R>10)

missing_C <- apply(replace_rows,2,percent_missing)
table(missing_C) #no concern here

replace_data <- replace_rows[,1:85]
leftout <- replace_rows[,86:91]

#check where the NAs are if needed
rindex <- rep(FALSE, nrow(replace_data))
for (i in 1:nrow(replace_data)){
  for (j in 1:grep("DGS_75",colnames(replace_data))){
    if( is.na(replace_data[i,j])){
      rindex[i] = TRUE
      j = ncol(replace_data)+1
    }
  }
}
data_error <- replace_data[rindex,]

rm(data_error)
#imputation
temp <- mice(replace_data)
fixed_data <- complete(temp)  #imputation using mice package
data <- cbind(fixed_data,leftout) #no additional participants were removed

rm(fixed_data,leftout,no_rows,replace_data,replace_rows)
}
```

```{r recode, include=FALSE}
##recode

#DGS recode
likert <- dict %>% 
  filter (value_label == "1 = Strongly disagree, 2 = Disagree, 3 = Somewhat disagree, 4 = Neither agree nor disagree, 5 = Somewhat agree, 6 = Agree, 7 = Strongly agree") %>%
  pull(variable)
add_likert <- function(x) {
  val_labels(x) <- c("Strongly disagree"= 1, "Disagree" = 2, "Somewhat disagree" = 3, "Neither agree nor disagree" = 4, "Somewhat agree" = 5, "Agree" = 6, "Strongly agree" = 7) 
  x
}
data <- data %>%
  mutate_at(likert, 
            add_likert)  

rm(likert, add_likert)

#HEXACO_C

likert <- dict %>% 
  filter (value_label == "1 = Strongly disagree, 2 = Somewhat disagree, 3 = Neither agree nor disagree, 4 = Somewhat agree, 5 = Strongly agree") %>%
  pull(variable)
add_likert <- function(x) {
  val_labels(x) <- c("Strongly disagree"= 1, "Somewhat disagree" = 2, "Neither agree nor disagree" = 3, "Somewhat agree" = 4, "Strongly agree" = 5) 
  x
}
data <- data %>%
  mutate_at(likert, 
            add_likert)  

rm(likert, add_likert)

## Reverse-scoring 
reversed_items <- dict %>%  #make a list of reversed items
 filter (keying == -1) %>% 
 pull(variable)

data <- data %>%  #reverse values in data
  mutate_at(reversed_items,
          reverse_labelled_values)

rm(reversed_items)

##scale construction

## Variable labels
var_label(data) <- dict %>% 
  select(variable, label) %>% 
  dict_to_list()

rm(extra)

##DGS
DGS <- dict %>% 
  filter (scale == "DGS") %>% 
  pull(variable)

data$DGS <- data %>% 
  select(all_of(DGS)) %>% 
  aggregate_and_document_scale()

##HEXACO_C

HEXACO_C <- dict %>% 
  filter (scale == "HEXACO_C") %>% 
  pull(variable)

data$HEXACO_C <- data %>% 
  select(all_of(HEXACO_C)) %>% 
  aggregate_and_document_scale()

###6 factors model
M6_1 <- dict %>% 
  filter (M6 == 1) %>% 
  pull(variable)
M6_2 <- dict %>% 
  filter (M6 == 2) %>% 
  pull(variable)
M6_3 <- dict %>% 
  filter (M6 == 3) %>% 
  pull(variable)
M6_4 <- dict %>% 
  filter (M6 == 4) %>% 
  pull(variable)
M6_5 <- dict %>% 
  filter (M6 == 5) %>% 
  pull(variable)
M6_6 <- dict %>% 
  filter (M6 == 6) %>% 
  pull(variable)

###6 factors model

data$M6_1 <- data %>% 
  select(all_of(M6_1)) %>% 
  aggregate_and_document_scale()

data$M6_2 <- data %>% 
  select(all_of(M6_2)) %>% 
  aggregate_and_document_scale()

data$M6_3 <- data %>% 
  select(all_of(M6_3)) %>% 
  aggregate_and_document_scale()

data$M6_4 <- data %>% 
  select(all_of(M6_4)) %>% 
  aggregate_and_document_scale()

data$M6_5 <- data %>% 
  select(all_of(M6_5)) %>% 
  aggregate_and_document_scale()

data$M6_6 <- data %>% 
  select(all_of(M6_6)) %>% 
  aggregate_and_document_scale()

#####Conscientiousness
Organization <- dict %>% 
  filter (subscale == "Organization") %>% 
  pull(variable)

Diligence <- dict %>% 
  filter (subscale == "Diligence") %>% 
  pull(variable)

Perfectionism <- dict %>% 
  filter (subscale == "Perfectionism") %>% 
  pull(variable)

Prudence <- dict %>% 
  filter (subscale == "Prudence") %>% 
  pull(variable)

data$Organization <- data %>% 
  dplyr::select(all_of(Organization)) %>% 
  aggregate_and_document_scale()

data$Diligence  <- data %>% 
  dplyr::select(all_of(Diligence)) %>% 
  aggregate_and_document_scale()

data$Perfectionism <- data %>% 
  dplyr::select(all_of(Perfectionism)) %>% 
  aggregate_and_document_scale()

data$Prudence <- data %>% 
  dplyr::select(all_of(Prudence)) %>% 
  aggregate_and_document_scale()

## Variable labels
var_label(data) <- dict %>% 
  dplyr::select(variable, label) %>% 
  dict_to_list()

###HEXACO factors
var_label(data$HEXACO_C) <- "10 items aggregated by rowMeans"
var_label(data$Diligence) <- "10 items aggregated by rowMeans"
var_label(data$Organization) <- "10 items aggregated by rowMeans"
var_label(data$Perfectionism) <- "10 items aggregated by rowMeans"
var_label(data$Prudence) <- "10 items aggregated by rowMeans"

```


```{r codebook}
metadata(data)$name <- "A short name for the data"
metadata(data)$description <- "Longer description of the dataset"
metadata(data)$temporalCoverage <- "Timespan of data collection" 

codebook(data, metadata_json = F, metadata_table = F) #generate codebook, excluding some messy meta-data
```

